sudo: false
language: ruby
cache: bundler
rvm:
- '2.3'
- '2.4'
- '2.5'
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install: gem install bundler
script:
- bundle install
- bundle exec rspec spec/
- bundle exec rubocop --fail-level A -S --format c --parallel
deploy:
  provider: rubygems
  gem: yaml-safe_load_stream
  api_key:
    secure: w1I8kCjTU8d/lgPsGWnC5ZyIUcBLJUUCi0aAVi6msA32Doda2eQWtL9OUMreVr4GO9F6/54cVPqrneyZtzqGtTzfYvss+yStNN/3Sac3X382piPPcOs5xuUewD50LPuLe8/gt72d9+dCuPibTIX0LVPNfdJCQeVH3I/od+THayQYIxUxWI6Jnp+j58KfB254IxrCqydjcRUsflDeCwPALNlPZHRBMmUBARWPTFsVdyoi5qhjOJEe9iWFwtjJ1vsQZIJKG4ErtAx1ycH+4gj5pMNM5+CMXuLD3K2Z1ecUBUpORik2QDHpG24VZDpa50L/P6mid7K/5rHW1lp9xT07SpoGdmJDfusN5dHFutc3ALr+NWht3A3eQW5Ew7zLMP8NAxYVStMZSWLCH+HKhLNAXZ7eaGAATX/Jc1LvuafqrHoPIisoub9qLUr/8Ke2DJejmjaBa7EnOd/01Fig/cZBNXf9u68UnwDIHCSMfO6GZ0Gq4hI5GbkPpQl+VQixTz9RyZsdmdfZ6hnUBgbSZ8s3/Y4yS4FRTNnLOqkztIyEXpyUo1tgAhYOzDaAH50eDLX+vW/KXDQKH2MYS64M9x83OnH+GTSgvARrX5nmALvoYku6r5aU3oRfvvmCbkR+Q+34aONnD0YcV3vRC8LBIjRlLOhpyPsQbt/We6rxDrzP2ug=
  on:
    tags: true
    rvm: '2.5'
